title: "Kubernetes実践入門"
summary: "Kubernetesの基本的な概念から、実際の運用に役立つノウハウまでを網羅した実践的なガイドブックです。"
topics: ["Kubernetes", "コンテナ", "Docker", "クラウドネイティブ"]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - 00_introduction
  - 01_setup_kind
  - 02_architecture
  - 03_cluster_inspection
  - 04_component_troubleshoot
  - 05_object_model_practice
